#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm

SETUP="frontend aabadmus
	bind *:80
	default_backend aabadmus-servers
backend aabadmus-servers
	balance roundrobin
	server 137476-web-01 52.86.95.250:80 check
	server 137476-web-02 100.26.50.214:80 check
"
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo echo /etc/haproxy/haproxy.cfg keep
echo "$SETUP" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
